# Generated by Django 5.2.7 on 2025-10-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_surfchat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surfchat',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='bookmark',
            name='channel_or_authors',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='snippet',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
